# Generated by Django 6.0.3 on 2026-04-03 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0002_complaint_category_complaint_priority'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='admin_response',
            field=models.TextField(blank=True, default='', help_text='Optional message visible to the user.'),
        ),
        migrations.AddField(
            model_name='complaint',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
